### ISSUE TITLE
Game Disc dumping takes longer than an eternity.

### ISSUE THREAD

**Issue by Atramentius** [dumpling-app/dumpling#11]
I am currently trying to dump my Breath of the wild game disc to a fat 32 formatted usb3.0 flashdrive. I started the dumping process yesterday at 4.00pm. Now its the next day at 8.00am and I am only done for 80%. The remainig time is estimaded to be around 18 more hours.
Before I started dumping it said that it could take UP TO 6hours for a game to dump, but this is insane. I really do not want to wait another day for this to finish, as I really trying to get some sleep, which is not possible with a wii u spinning a disc with 2000rpm right next to you.
Is there anyithnig i can do to fix this?

**Comment by CJK95** [comment]
I had the same issue with a SanDisk flash drive.   Switched to a transcend
external hdd - added a USB 3.0 power splitter cable - and use the front
ports.  No issues since.
.
Note that BoTW fully updated is a BIG game.   I want to say it was a 6 hour
dump. (most games without updates are 1-1.5 hours)

**Comment by Atramentius** [comment]
I used another tool instead. Disc2app. Only took 45mins to dump... so yeah. But thanks for the reply.

**Comment by Crementif** [comment]
Dumpling is indeed pretty slow at dumping BotW unfortunately due to technical reasons which I'd like to explain. Basically, writing many files to the Wii U's filesystem is a very big problem with the Wii U. Dumpling dumps it in an extracted form so that it's easier to use the files with Cemu, but unfortunately even with custom SD card drivers (in simple terms) to write to the SD card faster it's still not as fast.

This slowness is unfortunately super noticeable in Breath of the Wild, which has like 20x the files of a normal game. Some stuff could be improved, but it'll likely never be as fast as just writing 50 .app files or a .wud file (like disc2app does) unfortunately for those games. Maybe eventually I can look into improving performance even more then now, but I'd really only be doing it for BotW so I don't consider it that high priority.

I'm curious what is up with your dumping time though. It really only should take 4-6 hours for the whole game and DLCs to be dumped (which is another thing that the 45 minutes in disc2app wouldn't be dumping). As to why, I've got no clue. Might be the suggestion that @CJK95 gave here, or you're using an older version of Dumpling. Anyway, disc2app is still a useful tool, so I'm glad you still got it dumped 👍.
