### ISSUE TITLE
disk dump didnt work

### ISSUE THREAD

**Issue by LuigiXHero** [dumpling-app/dumpling#2]
I use cold boot haxchi, when I click the dump game disk option it just instantly freezes and I can't do anything but shut off my console. So I reverted back to classic and it worked. Game was botw.

**Comment by LuigiXHero** [comment]
So my wii u shut off during the old dumpling so I tried the new one again, mocha is apparently required for the new one too, but a warning would've been nice instead of just crashing.

**Comment by Crementif** [comment]
What version of dumpling did you download? Coldboot haxchi support was fixed in version 2.0.2, where it would prior take a super long time to load the app and make the disc screen freeze and not accept any inputs.

I'm asking because I'm genuinely curious as to how it doesn't work. Let me know and I can definitely look into it if the version you were using was newer then that. Thanks for reporting this!

**Comment by LuigiXHero** [comment]
It was the newest one as of my post so 2.0.3, sorry that I don't have any more info on it, it literally just hangs the moment I press dump disk.

**Comment by Crementif** [comment]
Yeah, I've identified the problem a while ago. Just haven't found time to fix it yet, since it's a considerable amount of stuff that would have to be changed.

**Comment by Crementif** [comment]
Fixed it in the latest update! Thanks for reporting the issue and answering my questions!
