### ISSUE TITLE
Disc dumping doesn't work on 2.1.0

### ISSUE THREAD

**Issue by aerthel** [dumpling-app/dumpling#6]
Using Disc dumping on latest release (2.1.0) never starts the process, stops at "Looking for a game disc ...". Dumpling doesn't crash/freeze, I can go back to the main menu pressing B. 
Tried putting the disc before and after using the Disc dump menu option, but to no avail. Also tried with and without using Mocha CFW first before launching dumpling, but it doesn't any change in behavior.
This WiiU has Haxchi installed, but i'm using the wiiuexploit.xyz method to launch HBL.

**Comment by Crementif** [comment]
Can you maybe try disc2app or wudumper and see if they also don't detect the disc? I'm using pretty similar methods for detecting whether a disc is inserted, so it not working is strange to me.

**Comment by aerthel** [comment]
Tested with FIX94/wudump 1.6, using wiiuexploit.xyz without Mocha, worked fine and it's currently dumping. Yesterday I tried using disc2app which also detected the disc just fine.

**Comment by Crementif** [comment]
Hmm, shit. I'll definitely try to replicate your issue, maybe I broke something last-minute or something.😅 

Thanks for reporting the issue so fast!

**Comment by Crementif** [comment]
Alright, found the problem and have fixed it, alongside some other problems! I'll push a new release that fixes this issue tomorrow, since there's one issue left.

In the rare case that you need/want a fixed version however, you could download it [here](https://cdn.discordapp.com/attachments/456165538771501056/780115207291928596/dumpling.rpx)!

**Comment by Serfrost** [comment]
> Alright, found the problem and have fixed it

Gg, that was pretty quick.

**Comment by Crementif** [comment]
New version (V2.1.1) should now work with discs (I think I've fixed this in a bugfix release like 3 times now, heh) properly. Thanks again!

Also, it shouldn't matter whether you use Mocha, Haxchi or none at all since Dumpling uses its own exploit variant since V2.1.0, which is why it also broke in that release hehe.

**Comment by aerthel** [comment]
Just tested on my end and discs are being detected now, thanks for the fix 👍
