### ISSUE TITLE
Can I use Dumpling to make a MLC dump instead of Wii U Nand Dumper?

### ISSUE THREAD

**Issue by ReubenBTalbott** [dumpling-app/dumpling#9]
I don't have an SD card large enough for a MLC dump but I have plenty of external USB drives. I have already backed up the other files except for the MLC using Wii U Nand Dumper and I was wondering if I can use Dumpling instead as it supports backing up to an external drive.

Thanks!
Reuben Talbott

**Comment by Crementif** [comment]
Yes, you can dump a decrypted version of the nand (aka MLC) using Dumpling to USB drives (as long as you format them with fat32). At least I added an option to do so. I'm not actually sure if it has ever been tested/used so I honestly wouldn't be surprised if it would fail half-way dumping or just last multiple days. Also, I'm not sure what you want to use these files for, since they can't be used to restore your Wii U.

**Comment by ReubenBTalbott** [comment]
Thanks for the answer! 
Sorry if it wasn't clear in my original message, but what I was ￼ specifically asking is if the MLC dump would be restorable in the event of a brick. I think it may be time to invest in a 64GB SD card.

**Comment by Crementif** [comment]
There isn't a way to restore NAND via software in general. Even if you use nand dumper it doesn't have an option to restore it. The reason why is probably some technical limitation of homebrew.

**Comment by ReubenBTalbott** [comment]
There is a way to restore a NAND dump using a Teensy and some fine soldering.

**Comment by emiyl** [comment]
I'm not sure dumpling is suitable for NAND restoring, as the backup would require to be re-encrypted into a format the Wii U would read. I would suggest either buying a larger SD card or finding/writing a Wii U NAND dumper that writes an encrypted image dump to a USB device (Probably much easier to just get a new SD card).

**Comment by Crementif** [comment]
Anyway, the answer is technically yes, so I'll be closing this issue. Feel free to continue asking any questions you've got though.
